import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;

public class AquariumApp {

    public static void main(String[] args) {

        SeaCreature[] tank = new SeaCreature[8];

        
        try {
            tank = loadSeaCreature("creatures.txt");
        } catch (IOException e) {
            System.out.println("Error reading creature data: " + e.getMessage());
        }
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }

        // Two starter creatures.
        /*
        //Nemo the fish, starting at position 4, moving right at speed 4, with symbol "><>"
        try{
            //tank[0] = new Fish("Nemo", 4, 4, 1, "><>");
        } 
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }

        //Dory the fish, starting at position 30, moving left at speed 2, with symbol "><((('>"
        try{
            //tank[1] = new Fish("Dory", 30, 2, -1, "><((('>");
        } 
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }

        //Sharky the shark, starting at position 15, moving right at speed 2, with symbol "⟩<^«⋗"
        try{
            //tank[2] = new Shark("Sharky", 15, 2, 1, "⟩<^«⋗");
        } 
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }

        //Terry the turtle, starting at position 6, moving left at speed 1, with symbol "🐢"
        try{
            //tank[3] = new Turtle("Terry", 6, 1, -1, "🐢");
        } 
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }
        
        //Bubbles the fish, starting at position 10, moving right at speed 2, with symbol "><>"
        try{
            //tank[4] = new Fish("Bubbles", 10, 2, 1, "><>");
        } 
        catch (InvalidCreatureException e) {
            System.out.println("Error creating creature: " + e.getMessage());
        }
        
        */
        
        // =====================================================
        // STUDENT TODO
        // =====================================================
        // 1. Create at least TWO additional SeaCreature subclasses.
        // 2. Add objects from those subclasses to this array.
        // 3. Make their movement behavior meaningfully different.
        //
        // Example once you create the class:
        // tank[2] = new Shark(...);
        // tank[3] = new Turtle(...);

        Aquarium aquarium = new Aquarium(tank);
        Scanner input = new Scanner(System.in);
        
        for (SeaCreature creature : tank) {
 	        if (creature != null) {
                         creature.move(Aquarium.TANK_WIDTH);
 	        }
        }

        boolean running = true;

        System.out.println("====================================");
        System.out.println("        JAVA TERMINAL AQUARIUM");
        System.out.println("====================================");

        boolean loop = false;

        while (running) {
            printMenu();
            System.out.print("Choose an option: ");
            String choice = input.nextLine().trim();

            switch (choice) {
                case "1":
                    aquarium.display();
                    break;

                case "2":
                    aquarium.advanceTurn();
                    aquarium.display();
                    break;

                case "3":
                    // Method to stop the free swim loop generated by AI model
                    loop = true;
                    while (loop) {
                        aquarium.advanceTurn();
                        aquarium.display();
                        try {
                            if (System.in.available() > 0 && "5".equals(input.nextLine().trim())) {
                                loop = false;
                            }
                            Thread.sleep(250);
                        } catch (IOException exception) {
                            loop = false;
                        } catch (InterruptedException exception) {
                            Thread.currentThread().interrupt();
                            loop = false;
                        }
                    }
                    break;

                case "4":
                    aquarium.listCreatureDetails();
                    break;

                case "5":
                    loop = false;
                    break;
                
                case "6":
                    running = false;
                    System.out.println("Aquarium closed. Goodbye!");
                    break;

                default:
                    System.out.println("Please choose 1, 2, 3, or 4.");
            }
        }

        input.close();
    }

    private static void printMenu() {
        System.out.println();
        System.out.println("1. View Aquarium");
        System.out.println("2. Advance One Turn");
        System.out.println("3. Free Swim");
        System.out.println("4. View Creature Details");
        System.out.println("5. Stop Free Swim");
        System.out.println("6. Quit");
    }
    public static SeaCreature[] loadSeaCreature(String filename) throws IOException, InvalidCreatureException {
        try (FileReader file = new FileReader(filename);
             Scanner inputs = new Scanner(file)) {

            int numCreatures = inputs.nextInt();
            inputs.nextLine();

            SeaCreature[] tank = new SeaCreature[numCreatures];

            for(int i = 0; i < tank.length; i++){
                String line = inputs.nextLine();
                tank[i] = createCreature(line);
            }

            return tank;
            }
    }

    public static SeaCreature createCreature(String line) throws InvalidCreatureException {

        try (Scanner inpu = new Scanner(line)) {
            inpu.useDelimiter(",");

            String creature = inpu.next();
            String name = inpu.next();
            int position = inpu.nextInt();
            int speed = inpu.nextInt();
            int direction = inpu.nextInt();
            String symbol = inpu.next();

            if (creature.equals("Fish")) {
                return new Fish(name, position, speed, direction, symbol);
            } else if (creature.equals("Shark")) {
                return new Shark(name, position, speed, direction, symbol);
            } else if (creature.equals("Turtle")) {
                return new Turtle(name, position, speed, direction, symbol);
            } else {
                throw new InvalidCreatureException("Invalid creature type: " + creature);
            }
        }

    }
}
